### ISSUE TITLE
Использование ассоциативных массивов

### ISSUE THREAD

**Issue by koorchik** [WebbyLab/php-validator-livr#15]
Есть проблема с LIVR, а вернее с ее реализацией:
https://packagist.org/packages/validator/livr

согласно спецификации rules должен быть
{
    name: 'required'
}

но реализация требует 
[
    name: 'required'
]

кроме того данные принимает только в виде ассоциативных массивов
а в виде объектов с полями нет

как валидировать сложный объект, например?

{
  "Delivery": {
    "name": "aaa",
    "items": [
       "item1": 12
    ]
  }
}

**Comment by k33nice** [comment]
Для валидации объекта его нужно привести к ассоциативному массиву.
Если объект - это экземпляр stdClass, то самым простым способом приведения (PHP >= 5.2)
```php
$object = (object)[
    'Delivery' => (object)[
        'name' => '
];

**Comment by koorchik** [comment]
Для валидации объекта его нужно привести к ассоциативному массиву.
Если объект - это экземпляр stdClass, то самым простым способом приведения (PHP >= 5.2)

$object = (object)[
    'Delivery' => (object)[
        'name' => '
];

**Comment by k33nice** [comment]
Для валидации объекта его нужно привести к ассоциативному массиву.
Если объект - это экземпляр stdClass или имеет только публичные свойства, то самым простым способом приведения (PHP >= 5.2) будет использование нативных JSON функций:
```php
$object = (object)[
    'Delivery' => (object)[
        'name' => 'aaa',
        'items' => [
            'item1' => 12
        ]
];

$array = json_decode(json_encode($object), true);
```

Для конвертации объекта содержащего приватные и/или защищенные свойства можно воспользоваться чем-то вроде этого:
```php
class YourObject
{
    protected $foo;
    private $bar;

    public function __construct($foo = null, $bar = null)
    {
        $this->foo = $foo;
        $this->bar = $bar;
    }
}

$obj = new YourObject('aaa', new YourObject('foo', 'bar'));

function objectToArray($object)
{
    if(!is_object($object) && !is_array($object)){
        return $object;
    }

    return array_map('objectToArray', (array)$object);
}

$array = objectToArray($obj);
/*
print_r($array);

Array
(
    [*foo] => aaa
    [YourObjectbar] => Array
        (
            [*foo] => foo
            [YourObjectbar] => bar
        )

)
 */
```
