### ISSUE TITLE
Add support of LIVR 2.0

### ISSUE THREAD

**Issue by koorchik** [WebbyLab/php-validator-livr#21]
### List of changes v2.0 (see spec for details)
- Switched to semver. New release version is 2.0
- Unified approach to types handling
- "Base rules" renamed to "Common rules".
- "Filter rules" renamed to "Modifiers". They do not validate anything, just modify data.
- "Helper rules" renamed to "Metarules" as this rules are for describing other rules
- Added common rule "any_object"
- Added string rule "string"
- Added string rule "eq"
- Added metarule "variable_object"
- Added metarule "or"
- Added modifier "default"
- Add more edge cases to test suite
- Add experimental status to the "like" rule

All you need is to update your implementation to pass the latest spec's test suite.

**Comment by koorchik** [comment]
Please, let me know when ready. I'll update spec README and will add line that your implementation is compatible with the latest version of LIVR

**Comment by koorchik** [comment]
Any updates?

**Comment by Shandur** [comment]
@koorchik Did you create a fork or something with the lib?

**Comment by koorchik** [comment]
It seems that v2 features were added to PHP implementation several years ago. So, the ticket can be closed! :)
